version: "3"
services:
  client_dev:
    build: ./client
    command: sh -c "npm run dev"
    container_name: pc-client-dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    working_dir: /home/app/client
    environment:
      API_URL: http://localhost:3001/v1
      NETWORK_API_URL: http://api_dev:3001/v1
  api_dev:
    build: ./api
    command: sh -c "npm run db-migrate && npm run run-dev"
    container_name: pc-api-dev
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: next-ts-jwt-boilerplate
      DB_HOST: db
      DB_PORT: 5432
      DB_TEST_HOST: db-test
    ports:
      - 3001:3001
    volumes:
      - ./api:/home/app/api
      - /home/app/api/node_modules
    working_dir: /home/app/api
    restart: on-failure
    depends_on:
      - db
      - db-test
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=next-ts-jwt-boilerplate
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=next-ts-jwt-boilerplate
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data-test/postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432
